### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PrzemyslawHausman** [Ruuv1337/BulkActions#1]
There is an error when i put this .dll file in paint.net\Effects folder and run Paint.net (v 4.0.12) in Settings > Plugin Errors

C:\Program Files\paint.net\Effects\BulkActionsForPaintDotNet.dll, version 1.1.0.0

Type: PDNBulkUpdater.PDNBulkUpdaterEffect
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: This exception has been generated by the stub loader for PDNBulkUpdater. Please disregard.
   at PDNBulkUpdater.PDNBulkUpdaterEffect..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PaintDotNet.Menus.EffectMenuBase.AddEffectsToMenu() in D:\src\pdn\src\PaintDotNet\Menus\EffectMenuBase.cs:line 602

**Comment by PrzemyslawHausman** [comment]
My bad, it works on paint.net  4.0.21
https://archive.org/details/paint.net.4.0.21.install
